name: Friends2_0
version: 2.2.1-ALPHA
author: HyChrod
main: de.HyChrod.Friends.Friends
commands:
  Friends:
    aliases: [freunde, freund, Friend, friends, friend, fre2711A]
    description: A completly new Friend-System!
  fre2711A: