#################################################
#												#
#    Plugin made by HyChrod, Version: 1.1.7 	#
#												#
#################################################

Friends:
  Prefix: "&6Friends &7|"
  CheckForUpdates: true
    
  FriendChat:
    Enable: true
    # The message have to start with this to write in the friend chat!
    Code: "@friends"

#################################################
#												#
#	You are not authorized to sell this Plugin	#
#	All rights reserved by HyChrod, 2016.		#
#												#
#################################################